# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = ProjectMQt
DESTDIR = ./x64/Debug
CONFIG += debug
LIBS += -L"../../../../../Qt/5.14.1/msvc2017_64/lib" \
    -l$(Qt_LIBS_) \
    -lopengl32
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
win32:RC_FILE = ProjectMQt.rc
RESOURCES = application.qrc